import { createServerFn } from '@tanstack/react-start';
import { z } from 'zod';
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware';
import { planErrors, planDiff, type PlanRecord } from './plan-editor';
async function checked(context:any) { const {requireAccountAdmin}=await import('./plan-access.server'); await requireAccountAdmin(context.userId); const {data:control,error}=await context.supabase.rpc('is_control',{_user_id:context.userId}); if(error||!control) throw new Error('Only admins who can edit access can manage plans'); const {supabaseAdmin}=await import('@/integrations/supabase/client.server'); return supabaseAdmin as any; }
export const getAdminPlans=createServerFn({method:'GET'}).middleware([requireSupabaseAuth]).handler(async({context})=>{ const sb=await checked(context); const [ps,rs,hs,cs,ss,us]=await Promise.all([sb.from('plans').select('*').order('role').order('sort'),sb.from('plan_reports').select('*'),sb.from('plan_history').select('*').order('at',{ascending:false}),sb.from('plan_changes').select('*').eq('status','scheduled'),sb.from('subscriptions').select('plan_id'),sb.from('users').select('id,first_name,last_name')]); if(ps.error) throw new Error(ps.error.message); const names=new Map((us.data??[]).map((u:any)=>[u.id,[u.first_name,u.last_name].filter(Boolean).join(' ')])); return {plans:(ps.data??[]).map((p:any)=>({...p,reports:(rs.data??[]).filter((r:any)=>r.plan_id===p.id),subscribers:(ss.data??[]).filter((s:any)=>s.plan_id===p.id).length,history:(hs.data??[]).filter((h:any)=>h.plan_id===p.id).map((h:any)=>({...h,byName:names.get(h.by_user)??'PitchSnack'})),scheduled:(cs.data??[]).find((c:any)=>c.plan_id===p.id)??null}))}; });
const report=z.object({report_key:z.enum(['fs5','fs3','fs1','verification','pnl','risk','credit']),mode:z.enum(['none','number','unlimited','contract']),per_term:z.number().int().min(1).nullable()});
const number=z.number().min(0).nullable(); const mode=z.enum(['none','number','unlimited','contract','bundles']).nullable();
const copy=z.object({badge:z.string().max(200),intent:z.string().max(500),points:z.array(z.string().max(1000)).max(30)});
const values=z.object({name:z.string().max(100),status:z.enum(['live','hidden']),price_type:z.enum(['free','paid','on_request']),price_thb:number,term_months:z.union([z.literal(1),z.literal(3),z.literal(6),z.literal(12)]),completion_fee_pct:number,value_cap_thb_m:number,requests_mode:mode,requests_n:number,clients_mode:mode,clients_n:number,users_mode:mode,users_n:number,mandates_mode:mode,mandates_n:number,verification_mode:z.enum(['included','paid','none']).nullable(),verification_price_thb:number,has_data_room:z.boolean(),has_manager:z.boolean(),has_valuation_video:z.boolean(),has_site_visit:z.boolean(),has_shortlists:z.boolean(),has_screening:z.boolean(),badge_style:z.enum(['entry','blue','navy_gold','sky','royal','deepnavy_gold','lightteal','teal_gold']),card_style:z.enum(['sage','amber_promo','blue','navy','sky','royal','deepnavy','lightteal','deepteal']),card_text:z.object({en:copy,th:copy}),reports:z.array(report)});
export const publishPlan=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((d)=>z.object({id:z.string().uuid(),values,keepPrice:z.enum(['renewal','stay']),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(),expectedAt:z.string()}).parse(d)).handler(async({data,context})=>{ const sb=await checked(context); const {data:current,error}=await sb.from('plans').select('*').eq('id',data.id).single(); if(error||!current) throw new Error('Plan not found'); if(current.updated_at!==data.expectedAt) throw new Error('This plan changed. Reload before publishing.'); const {data:rs}=await sb.from('plan_reports').select('*').eq('plan_id',data.id); const draft={...current,...data.values}; const errs=planErrors(draft); if(Object.keys(errs).length) throw new Error(Object.values(errs)[0]); const diff=planDiff({...current,reports:rs??[]} as PlanRecord,draft); const summary=diff.map(c=>`${c.label}: ${c.old??'Any value'} → ${c.new??'Any value'}`).join(' · ')||'Plan published'; const newValues={...data.values,_summary:summary}; if(data.date){const effective=new Date(`${data.date}T00:00:00+07:00`); const today=new Date(Date.now()+7*3600000).toISOString().slice(0,10); if(data.date<=today) throw new Error('Choose tomorrow or a later date.'); const {error:e}=await sb.from('plan_changes').insert({plan_id:data.id,new_values:newValues,effective_at:effective.toISOString(),keep_price:data.keepPrice,created_by:context.userId}); if(e) throw new Error(e.message); await sb.from('plan_history').insert({plan_id:data.id,by_user:context.userId,summary:`Scheduled for ${data.date}: ${summary}`,changes:diff}); }else{const {error:e}=await sb.rpc('apply_plan_edit',{_plan:data.id,_values:newValues,_by:context.userId,_keep:data.keepPrice}); if(e) throw new Error(e.message);} return {ok:true,summary}; });
export const cancelPlanChange=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(d=>z.object({id:z.string().uuid()}).parse(d)).handler(async({data,context})=>{const sb=await checked(context); const {data:r,error}=await sb.from('plan_changes').update({status:'cancelled'}).eq('id',data.id).eq('status','scheduled').select('plan_id').single(); if(error) throw new Error(error.message); await sb.from('plan_history').insert({plan_id:r.plan_id,by_user:context.userId,summary:'Scheduled change cancelled'}); return {ok:true};});
export const createPlan=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(d=>z.object({role:z.enum(['seller','buyer','advisor'])}).parse(d)).handler(async({data,context})=>{const sb=await checked(context); const {data:rows}=await sb.from('plans').select('sort').eq('role',data.role).order('sort',{ascending:false}).limit(1); const {data:p,error}=await sb.from('plans').insert({role:data.role,key:`custom_${crypto.randomUUID()}`,name:'New plan',status:'hidden',sort:(rows?.[0]?.sort??0)+1,price_type:'free',term_months:12,completion_fee_pct:data.role==='seller'?1.25:null,requests_mode:data.role==='buyer'?'bundles':data.role==='seller'?'none':'number',requests_n:data.role==='advisor'?1:null,card_style:data.role==='seller'?'sage':data.role==='buyer'?'sky':'lightteal',badge_style:data.role==='seller'?'entry':data.role==='buyer'?'sky':'lightteal'}).select('*').single(); if(error) throw new Error(error.message); await sb.from('plan_history').insert({plan_id:p.id,by_user:context.userId,summary:'New plan · not published'}); return {id:p.id};});
