export type PlanRole = 'seller' | 'buyer' | 'advisor';
export type CardLang = 'en' | 'th';
export type CardCopy = { badge: string; intent: string; points: string[] };
export type PlanRecord = { id: string; role: PlanRole; key: string; name: string; status: string; sort: number; price_type: string; price_thb: number | null; term_months: number; completion_fee_pct: number | null; value_cap_thb_m: number | null; requests_mode: string; requests_n: number | null; card_style: string; card_text: Record<CardLang, CardCopy>; badge_style: string; updated_at: string; [key: string]: any };
export const REPORTS = [{key:'fs5',label:'Financial statements · 5 years'}, {key:'fs3',label:'Financial statements · 3 years'}, {key:'fs1',label:'Financial statements · 1 year'}, {key:'verification',label:'Company and registration verification'}, {key:'pnl',label:'Company P&L analysis report'}, {key:'risk',label:'Company risk report'}, {key:'credit',label:'Company credit report'}];
export const LABELS: Record<string,string> = {name:'Name',status:'Status',price_type:'Price type',price_thb:'Price',term_months:'Term',completion_fee_pct:'Completion fee',value_cap_thb_m:'Business value',requests_mode:'Contact requests',requests_n:'Contact requests',clients_mode:'Clients',clients_n:'Clients',users_mode:'Users',users_n:'Users',mandates_mode:'Mandates',mandates_n:'Mandates',verification_mode:'Company verification',verification_price_thb:'Verification price',has_data_room:'Teaser and data room',has_manager:'Dedicated manager',has_valuation_video:'Valuation and pitch video',has_site_visit:'Site visit',has_shortlists:'Matched shortlists',has_screening:'Screening reports',badge_style:'Badge colour',card_style:'Card colour',card_text:'Card text'};
export function planPrice(p: PlanRecord,lang:CardLang='en') { if(p.price_type==='free') return lang==='en'?'Free':'ฟรี'; if(p.price_type==='on_request') return lang==='en'?'On request':'ตามข้อเสนอ'; return `${Number(p.price_thb??0).toLocaleString('en-US')} ${lang==='en'?'THB':'บาท'} / ${p.term_months===12?(lang==='en'?'yr':'ปี'):`${p.term_months} ${lang==='en'?'mo':'เดือน'}`}`; }
export function planChip(p:PlanRecord,lang:CardLang='en') { return p.value_cap_thb_m==null ? (lang==='en'?'Business selling price: any value':'ราคาขายกิจการ: ทุกมูลค่า') : (lang==='en'?`Business selling price below THB ${p.value_cap_thb_m}m`:`ราคาขายกิจการต่ำกว่า ${p.value_cap_thb_m} ล้านบาท`); }
export function termWords(p:PlanRecord) {return p.term_months===12?'a year':p.term_months===1?'a month':`every ${p.term_months} months`;}
export function modeText(mode:string,n:number|null,p:PlanRecord) {return mode==='number'?`${n} ${termWords(p)}`:mode==='none'?'Not included':mode==='bundles'?'Bought in bundles':mode==='contract'?'As agreed in the contract':'Unlimited';}
export function planErrors(p:PlanRecord):Record<string,string> { const e:Record<string,string>={}; if(!p.name.trim()) e.name='Give the plan a name.'; if(p.price_type==='paid'&&!((p.price_thb??0)>0)) e.price_thb='Enter a price above 0, or choose Free or On request.'; if(p.role==='seller'&&(p.completion_fee_pct==null||p.completion_fee_pct<0)) e.completion_fee_pct='Enter the completion fee, for example 1.25.'; for(const k of ['requests','clients','users','mandates']) if(p[`${k}_mode`]==='number'&&(!(p[`${k}_n`]>0)||!Number.isInteger(p[`${k}_n`]))) e[`${k}_n`]='Enter at least 1, or choose another option.'; if(p.verification_mode==='paid'&&!(p.verification_price_thb>0)) e.verification_price_thb='Enter the report price, or choose another option.'; for(const r of p.reports??[]) if(r.mode==='number'&&(!(r.per_term>0)||!Number.isInteger(r.per_term))) e[r.report_key]='Enter at least 1, or choose another option.'; return e; }
export function planDiff(old:PlanRecord,next:PlanRecord) {const changes:{key:string,label:string,old:any,new:any}[]=[]; for(const key of Object.keys(LABELS)) {if(key==='card_text'){for(const lang of ['th','en'] as CardLang[]) if(JSON.stringify(old.card_text?.[lang])!==JSON.stringify(next.card_text?.[lang])) changes.push({key:`card_text.${lang}`,label:`Card text (${lang==='th'?'Thai':'English'})`,old:'Previous text',new:'Updated'});}else if(JSON.stringify(old[key])!==JSON.stringify(next[key])){const m=key.match(/^(requests|clients|users|mandates)_(n|mode)$/); if(m){if(m[2]==='mode'&&JSON.stringify(old[`${m[1]}_n`])!==JSON.stringify(next[`${m[1]}_n`])) continue; changes.push({key,label:LABELS[key],old:modeText(old[`${m[1]}_mode`],old[`${m[1]}_n`],old),new:modeText(next[`${m[1]}_mode`],next[`${m[1]}_n`],next)});} else changes.push({key,label:LABELS[key],old:old[key],new:next[key]});}} for(const r of next.reports??[]){const prev=(old.reports??[]).find((x:any)=>x.report_key===r.report_key); if(prev?.mode!==r.mode||prev?.per_term!==r.per_term) changes.push({key:r.report_key,label:REPORTS.find(x=>x.key===r.report_key)?.label??r.report_key,old:modeText(prev?.mode??'none',prev?.per_term??null,old),new:modeText(r.mode,r.per_term,next)});}return changes;}
export const STYLES:Record<PlanRole,string[]>={seller:['sage','amber_promo','blue','navy'],buyer:['sky','royal','deepnavy'],advisor:['lightteal','deepteal']};
