export type LoginLang = "th" | "en";
type C = { th: string; en: string };
const c = (th: string, en: string): C => ({ th, en });

export const L = {
  title: c("PitchSnack · เข้าสู่ระบบ", "PitchSnack · Sign in"),
  logo: c("PitchSnack · กลับไปหน้าแรก", "PitchSnack · Back to the homepage"),
  chipA: c("กิจการท้องถิ่น · ", "Local businesses · "),
  chipB: c("ส่งต่ออย่างเป็นความลับ", "handed on in confidence"),
  h1: c("สร้างมาทั้งชีวิต", "Built over a lifetime."),
  h2: c("ส่งต่อให้ถูกมือ", "Handed to the right hands."),
  intro: c(
    "เข้าสู่ระบบเพื่อดูการจับคู่ คำขอติดต่อ และห้องข้อมูลของท่าน ชื่อของทั้งสองฝ่ายยังเป็นความลับ จนกว่าจะลงนาม NDA",
    "Sign in to see your matches, contact requests and data room. Names on both sides stay private until an NDA is signed.",
  ),
  p1: c("ตรวจสอบผู้ขายและผู้ซื้อทุกรายกับทะเบียน DBD", "Every seller and buyer checked against the DBD register"),
  p2: c("ห้องข้อมูลเปิดเมื่อเจ้าของกิจการพร้อมเท่านั้น", "The data room opens only when the owner is ready"),
  p3: c("ไม่ถือเงิน และไม่เข้าข้างฝ่ายใด", "No funds held, no side taken"),
  signs: [
    c("โรงสีข้าว", "RICE MILL"), c("ร้านกาแฟ", "COFFEE"), c("คลินิก", "CLINIC"),
    c("โรงแรม", "HOTEL"), c("อะไหล่ยนต์", "AUTO PARTS"), c("บรรจุภัณฑ์", "PACKAGING"),
  ],
  back: c("กลับไปหน้าแรก", "Back to the homepage"),
  card: c("ยินดีต้อนรับกลับมา", "Welcome back"),
  cline: c("เข้าสู่ระบบเพื่อติดตามดีลของท่านต่อจากเดิม", "Sign in to pick up your deals where you left off."),
  email: c("อีเมล", "Email address"),
  emailPh: c("you@company.co.th", "you@company.com"),
  pw: c("รหัสผ่าน", "Password"),
  forgot: c("ลืมรหัสผ่าน?", "Forgot password?"),
  pwPh: c("กรอกรหัสผ่าน", "Enter your password"),
  show: c("แสดงรหัสผ่าน", "Show password"),
  hide: c("ซ่อนรหัสผ่าน", "Hide password"),
  remember: c("จดจำฉันไว้ในอุปกรณ์นี้", "Keep me signed in on this device"),
  btn: c("เข้าสู่ระบบ", "Sign in"),
  busy: c("กำลังเข้าสู่ระบบ…", "Signing in…"),
  emailErr: c("กรุณากรอกอีเมลให้ถูกต้อง เช่น name@company.co.th", "Enter a valid email address, for example name@company.com"),
  pwErr: c("กรุณากรอกรหัสผ่าน", "Enter your password"),
  wrong: c("อีเมลหรือรหัสผ่านไม่ถูกต้อง", "The email or password is incorrect."),
  other: c("ไม่สามารถเข้าสู่ระบบได้ในขณะนี้ กรุณาลองอีกครั้ง", "Unable to sign in right now. Please try again."),
  sso: c("ยังไม่ได้ตั้งค่า SSO / SAML สำหรับพื้นที่ทำงานนี้ กรุณาติดต่อผู้ดูแลระบบ", "SSO / SAML sign-in is not configured for this workspace yet. Contact your administrator."),
  divider: c("หรือเข้าสู่ระบบด้วย", "or sign in with"),
  noAcc: c("ยังไม่มีบัญชี?", "No account?"),
  signUp: c("สมัครใช้งาน", "Sign up"),
  fineA: c("การเข้าสู่ระบบถือว่าท่านยอมรับ ", "By signing in, you agree to our "),
  terms: c("ข้อกำหนดการใช้งาน", "Terms of Service"),
  and: c(" และ ", " and "),
  privacy: c("นโยบายความเป็นส่วนตัว", "Privacy Policy"),
  fineB: c("", "."),
} as const;
