/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as Sp2GatewayIndexRouteImport } from './routes/sp2-gateway/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedStartupsRouteImport } from './routes/_authenticated/startups'
import { Route as AuthenticatedSharedDealsRouteImport } from './routes/_authenticated/shared-deals'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated/preferences'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedInvestorsRouteImport } from './routes/_authenticated/investors'
import { Route as AuthenticatedIntakeQueueRouteImport } from './routes/_authenticated/intake-queue'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAccessManagementRouteImport } from './routes/_authenticated/access-management'
import { Route as AuthenticatedStartupsIndexRouteImport } from './routes/_authenticated/startups.index'
import { Route as AuthenticatedSharedDealsIndexRouteImport } from './routes/_authenticated/shared-deals.index'
import { Route as AuthenticatedInvestorsIndexRouteImport } from './routes/_authenticated/investors.index'
import { Route as AuthenticatedGlobalStartupsIndexRouteImport } from './routes/_authenticated/global-startups.index'
import { Route as AuthenticatedDealsIndexRouteImport } from './routes/_authenticated/deals.index'
import { Route as AuthenticatedStartupsNewRouteImport } from './routes/_authenticated/startups.new'
import { Route as AuthenticatedStartupsIdRouteImport } from './routes/_authenticated/startups.$id'
import { Route as AuthenticatedSharedDealsIdRouteImport } from './routes/_authenticated/shared-deals.$id'
import { Route as AuthenticatedSettingsDefaultIntakeRouteImport } from './routes/_authenticated/settings.default-intake'
import { Route as AuthenticatedInvestorsNewRouteImport } from './routes/_authenticated/investors.new'
import { Route as AuthenticatedInvestorsIdRouteImport } from './routes/_authenticated/investors.$id'
import { Route as AuthenticatedGlobalStartupsBrowseRouteImport } from './routes/_authenticated/global-startups.browse'
import { Route as AuthenticatedGlobalStartupsIdRouteImport } from './routes/_authenticated/global-startups.$id'
import { Route as AuthenticatedDealsNewRouteImport } from './routes/_authenticated/deals.new'
import { Route as AuthenticatedDealsIdRouteImport } from './routes/_authenticated/deals.$id'
import { Route as AuthenticatedStartupsIdIndexRouteImport } from './routes/_authenticated/startups.$id.index'
import { Route as AuthenticatedInvestorsIdIndexRouteImport } from './routes/_authenticated/investors.$id.index'
import { Route as AuthenticatedDealsIdIndexRouteImport } from './routes/_authenticated/deals.$id.index'
import { Route as AuthenticatedStartupsIdEditRouteImport } from './routes/_authenticated/startups.$id.edit'
import { Route as AuthenticatedInvestorsIdEditRouteImport } from './routes/_authenticated/investors.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const Sp2GatewayIndexRoute = Sp2GatewayIndexRouteImport.update({
  id: '/sp2-gateway/',
  path: '/sp2-gateway/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStartupsRoute = AuthenticatedStartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSharedDealsRoute =
  AuthenticatedSharedDealsRouteImport.update({
    id: '/shared-deals',
    path: '/shared-deals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvestorsRoute = AuthenticatedInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntakeQueueRoute =
  AuthenticatedIntakeQueueRouteImport.update({
    id: '/intake-queue',
    path: '/intake-queue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccessManagementRoute =
  AuthenticatedAccessManagementRouteImport.update({
    id: '/access-management',
    path: '/access-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStartupsIndexRoute =
  AuthenticatedStartupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStartupsRoute,
  } as any)
const AuthenticatedSharedDealsIndexRoute =
  AuthenticatedSharedDealsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSharedDealsRoute,
  } as any)
const AuthenticatedInvestorsIndexRoute =
  AuthenticatedInvestorsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInvestorsRoute,
  } as any)
const AuthenticatedGlobalStartupsIndexRoute =
  AuthenticatedGlobalStartupsIndexRouteImport.update({
    id: '/global-startups/',
    path: '/global-startups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDealsIndexRoute = AuthenticatedDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDealsRoute,
} as any)
const AuthenticatedStartupsNewRoute =
  AuthenticatedStartupsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedStartupsRoute,
  } as any)
const AuthenticatedStartupsIdRoute = AuthenticatedStartupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStartupsRoute,
} as any)
const AuthenticatedSharedDealsIdRoute =
  AuthenticatedSharedDealsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSharedDealsRoute,
  } as any)
const AuthenticatedSettingsDefaultIntakeRoute =
  AuthenticatedSettingsDefaultIntakeRouteImport.update({
    id: '/settings/default-intake',
    path: '/settings/default-intake',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvestorsNewRoute =
  AuthenticatedInvestorsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInvestorsRoute,
  } as any)
const AuthenticatedInvestorsIdRoute =
  AuthenticatedInvestorsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedInvestorsRoute,
  } as any)
const AuthenticatedGlobalStartupsBrowseRoute =
  AuthenticatedGlobalStartupsBrowseRouteImport.update({
    id: '/global-startups/browse',
    path: '/global-startups/browse',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGlobalStartupsIdRoute =
  AuthenticatedGlobalStartupsIdRouteImport.update({
    id: '/global-startups/$id',
    path: '/global-startups/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDealsNewRoute = AuthenticatedDealsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedDealsRoute,
} as any)
const AuthenticatedDealsIdRoute = AuthenticatedDealsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDealsRoute,
} as any)
const AuthenticatedStartupsIdIndexRoute =
  AuthenticatedStartupsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStartupsIdRoute,
  } as any)
const AuthenticatedInvestorsIdIndexRoute =
  AuthenticatedInvestorsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInvestorsIdRoute,
  } as any)
const AuthenticatedDealsIdIndexRoute =
  AuthenticatedDealsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDealsIdRoute,
  } as any)
const AuthenticatedStartupsIdEditRoute =
  AuthenticatedStartupsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedStartupsIdRoute,
  } as any)
const AuthenticatedInvestorsIdEditRoute =
  AuthenticatedInvestorsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedInvestorsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/access-management': typeof AuthenticatedAccessManagementRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRouteWithChildren
  '/intake-queue': typeof AuthenticatedIntakeQueueRoute
  '/investors': typeof AuthenticatedInvestorsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/shared-deals': typeof AuthenticatedSharedDealsRouteWithChildren
  '/startups': typeof AuthenticatedStartupsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/sp2-gateway/': typeof Sp2GatewayIndexRoute
  '/deals/$id': typeof AuthenticatedDealsIdRouteWithChildren
  '/deals/new': typeof AuthenticatedDealsNewRoute
  '/global-startups/$id': typeof AuthenticatedGlobalStartupsIdRoute
  '/global-startups/browse': typeof AuthenticatedGlobalStartupsBrowseRoute
  '/investors/$id': typeof AuthenticatedInvestorsIdRouteWithChildren
  '/investors/new': typeof AuthenticatedInvestorsNewRoute
  '/settings/default-intake': typeof AuthenticatedSettingsDefaultIntakeRoute
  '/shared-deals/$id': typeof AuthenticatedSharedDealsIdRoute
  '/startups/$id': typeof AuthenticatedStartupsIdRouteWithChildren
  '/startups/new': typeof AuthenticatedStartupsNewRoute
  '/deals/': typeof AuthenticatedDealsIndexRoute
  '/global-startups/': typeof AuthenticatedGlobalStartupsIndexRoute
  '/investors/': typeof AuthenticatedInvestorsIndexRoute
  '/shared-deals/': typeof AuthenticatedSharedDealsIndexRoute
  '/startups/': typeof AuthenticatedStartupsIndexRoute
  '/investors/$id/edit': typeof AuthenticatedInvestorsIdEditRoute
  '/startups/$id/edit': typeof AuthenticatedStartupsIdEditRoute
  '/deals/$id/': typeof AuthenticatedDealsIdIndexRoute
  '/investors/$id/': typeof AuthenticatedInvestorsIdIndexRoute
  '/startups/$id/': typeof AuthenticatedStartupsIdIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/access-management': typeof AuthenticatedAccessManagementRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/intake-queue': typeof AuthenticatedIntakeQueueRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/sp2-gateway': typeof Sp2GatewayIndexRoute
  '/deals/new': typeof AuthenticatedDealsNewRoute
  '/global-startups/$id': typeof AuthenticatedGlobalStartupsIdRoute
  '/global-startups/browse': typeof AuthenticatedGlobalStartupsBrowseRoute
  '/investors/new': typeof AuthenticatedInvestorsNewRoute
  '/settings/default-intake': typeof AuthenticatedSettingsDefaultIntakeRoute
  '/shared-deals/$id': typeof AuthenticatedSharedDealsIdRoute
  '/startups/new': typeof AuthenticatedStartupsNewRoute
  '/deals': typeof AuthenticatedDealsIndexRoute
  '/global-startups': typeof AuthenticatedGlobalStartupsIndexRoute
  '/investors': typeof AuthenticatedInvestorsIndexRoute
  '/shared-deals': typeof AuthenticatedSharedDealsIndexRoute
  '/startups': typeof AuthenticatedStartupsIndexRoute
  '/investors/$id/edit': typeof AuthenticatedInvestorsIdEditRoute
  '/startups/$id/edit': typeof AuthenticatedStartupsIdEditRoute
  '/deals/$id': typeof AuthenticatedDealsIdIndexRoute
  '/investors/$id': typeof AuthenticatedInvestorsIdIndexRoute
  '/startups/$id': typeof AuthenticatedStartupsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/access-management': typeof AuthenticatedAccessManagementRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deals': typeof AuthenticatedDealsRouteWithChildren
  '/_authenticated/intake-queue': typeof AuthenticatedIntakeQueueRoute
  '/_authenticated/investors': typeof AuthenticatedInvestorsRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/shared-deals': typeof AuthenticatedSharedDealsRouteWithChildren
  '/_authenticated/startups': typeof AuthenticatedStartupsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/sp2-gateway/': typeof Sp2GatewayIndexRoute
  '/_authenticated/deals/$id': typeof AuthenticatedDealsIdRouteWithChildren
  '/_authenticated/deals/new': typeof AuthenticatedDealsNewRoute
  '/_authenticated/global-startups/$id': typeof AuthenticatedGlobalStartupsIdRoute
  '/_authenticated/global-startups/browse': typeof AuthenticatedGlobalStartupsBrowseRoute
  '/_authenticated/investors/$id': typeof AuthenticatedInvestorsIdRouteWithChildren
  '/_authenticated/investors/new': typeof AuthenticatedInvestorsNewRoute
  '/_authenticated/settings/default-intake': typeof AuthenticatedSettingsDefaultIntakeRoute
  '/_authenticated/shared-deals/$id': typeof AuthenticatedSharedDealsIdRoute
  '/_authenticated/startups/$id': typeof AuthenticatedStartupsIdRouteWithChildren
  '/_authenticated/startups/new': typeof AuthenticatedStartupsNewRoute
  '/_authenticated/deals/': typeof AuthenticatedDealsIndexRoute
  '/_authenticated/global-startups/': typeof AuthenticatedGlobalStartupsIndexRoute
  '/_authenticated/investors/': typeof AuthenticatedInvestorsIndexRoute
  '/_authenticated/shared-deals/': typeof AuthenticatedSharedDealsIndexRoute
  '/_authenticated/startups/': typeof AuthenticatedStartupsIndexRoute
  '/_authenticated/investors/$id/edit': typeof AuthenticatedInvestorsIdEditRoute
  '/_authenticated/startups/$id/edit': typeof AuthenticatedStartupsIdEditRoute
  '/_authenticated/deals/$id/': typeof AuthenticatedDealsIdIndexRoute
  '/_authenticated/investors/$id/': typeof AuthenticatedInvestorsIdIndexRoute
  '/_authenticated/startups/$id/': typeof AuthenticatedStartupsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/access-management'
    | '/audit'
    | '/connections'
    | '/dashboard'
    | '/deals'
    | '/intake-queue'
    | '/investors'
    | '/notifications'
    | '/preferences'
    | '/security'
    | '/shared-deals'
    | '/startups'
    | '/users'
    | '/sp2-gateway/'
    | '/deals/$id'
    | '/deals/new'
    | '/global-startups/$id'
    | '/global-startups/browse'
    | '/investors/$id'
    | '/investors/new'
    | '/settings/default-intake'
    | '/shared-deals/$id'
    | '/startups/$id'
    | '/startups/new'
    | '/deals/'
    | '/global-startups/'
    | '/investors/'
    | '/shared-deals/'
    | '/startups/'
    | '/investors/$id/edit'
    | '/startups/$id/edit'
    | '/deals/$id/'
    | '/investors/$id/'
    | '/startups/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/access-management'
    | '/audit'
    | '/connections'
    | '/dashboard'
    | '/intake-queue'
    | '/notifications'
    | '/preferences'
    | '/security'
    | '/users'
    | '/'
    | '/sp2-gateway'
    | '/deals/new'
    | '/global-startups/$id'
    | '/global-startups/browse'
    | '/investors/new'
    | '/settings/default-intake'
    | '/shared-deals/$id'
    | '/startups/new'
    | '/deals'
    | '/global-startups'
    | '/investors'
    | '/shared-deals'
    | '/startups'
    | '/investors/$id/edit'
    | '/startups/$id/edit'
    | '/deals/$id'
    | '/investors/$id'
    | '/startups/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/access-management'
    | '/_authenticated/audit'
    | '/_authenticated/connections'
    | '/_authenticated/dashboard'
    | '/_authenticated/deals'
    | '/_authenticated/intake-queue'
    | '/_authenticated/investors'
    | '/_authenticated/notifications'
    | '/_authenticated/preferences'
    | '/_authenticated/security'
    | '/_authenticated/shared-deals'
    | '/_authenticated/startups'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/sp2-gateway/'
    | '/_authenticated/deals/$id'
    | '/_authenticated/deals/new'
    | '/_authenticated/global-startups/$id'
    | '/_authenticated/global-startups/browse'
    | '/_authenticated/investors/$id'
    | '/_authenticated/investors/new'
    | '/_authenticated/settings/default-intake'
    | '/_authenticated/shared-deals/$id'
    | '/_authenticated/startups/$id'
    | '/_authenticated/startups/new'
    | '/_authenticated/deals/'
    | '/_authenticated/global-startups/'
    | '/_authenticated/investors/'
    | '/_authenticated/shared-deals/'
    | '/_authenticated/startups/'
    | '/_authenticated/investors/$id/edit'
    | '/_authenticated/startups/$id/edit'
    | '/_authenticated/deals/$id/'
    | '/_authenticated/investors/$id/'
    | '/_authenticated/startups/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Sp2GatewayIndexRoute: typeof Sp2GatewayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sp2-gateway/': {
      id: '/sp2-gateway/'
      path: '/sp2-gateway'
      fullPath: '/sp2-gateway/'
      preLoaderRoute: typeof Sp2GatewayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/startups': {
      id: '/_authenticated/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof AuthenticatedStartupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shared-deals': {
      id: '/_authenticated/shared-deals'
      path: '/shared-deals'
      fullPath: '/shared-deals'
      preLoaderRoute: typeof AuthenticatedSharedDealsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investors': {
      id: '/_authenticated/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof AuthenticatedInvestorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intake-queue': {
      id: '/_authenticated/intake-queue'
      path: '/intake-queue'
      fullPath: '/intake-queue'
      preLoaderRoute: typeof AuthenticatedIntakeQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/access-management': {
      id: '/_authenticated/access-management'
      path: '/access-management'
      fullPath: '/access-management'
      preLoaderRoute: typeof AuthenticatedAccessManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/startups/': {
      id: '/_authenticated/startups/'
      path: '/'
      fullPath: '/startups/'
      preLoaderRoute: typeof AuthenticatedStartupsIndexRouteImport
      parentRoute: typeof AuthenticatedStartupsRoute
    }
    '/_authenticated/shared-deals/': {
      id: '/_authenticated/shared-deals/'
      path: '/'
      fullPath: '/shared-deals/'
      preLoaderRoute: typeof AuthenticatedSharedDealsIndexRouteImport
      parentRoute: typeof AuthenticatedSharedDealsRoute
    }
    '/_authenticated/investors/': {
      id: '/_authenticated/investors/'
      path: '/'
      fullPath: '/investors/'
      preLoaderRoute: typeof AuthenticatedInvestorsIndexRouteImport
      parentRoute: typeof AuthenticatedInvestorsRoute
    }
    '/_authenticated/global-startups/': {
      id: '/_authenticated/global-startups/'
      path: '/global-startups'
      fullPath: '/global-startups/'
      preLoaderRoute: typeof AuthenticatedGlobalStartupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deals/': {
      id: '/_authenticated/deals/'
      path: '/'
      fullPath: '/deals/'
      preLoaderRoute: typeof AuthenticatedDealsIndexRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
    '/_authenticated/startups/new': {
      id: '/_authenticated/startups/new'
      path: '/new'
      fullPath: '/startups/new'
      preLoaderRoute: typeof AuthenticatedStartupsNewRouteImport
      parentRoute: typeof AuthenticatedStartupsRoute
    }
    '/_authenticated/startups/$id': {
      id: '/_authenticated/startups/$id'
      path: '/$id'
      fullPath: '/startups/$id'
      preLoaderRoute: typeof AuthenticatedStartupsIdRouteImport
      parentRoute: typeof AuthenticatedStartupsRoute
    }
    '/_authenticated/shared-deals/$id': {
      id: '/_authenticated/shared-deals/$id'
      path: '/$id'
      fullPath: '/shared-deals/$id'
      preLoaderRoute: typeof AuthenticatedSharedDealsIdRouteImport
      parentRoute: typeof AuthenticatedSharedDealsRoute
    }
    '/_authenticated/settings/default-intake': {
      id: '/_authenticated/settings/default-intake'
      path: '/settings/default-intake'
      fullPath: '/settings/default-intake'
      preLoaderRoute: typeof AuthenticatedSettingsDefaultIntakeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investors/new': {
      id: '/_authenticated/investors/new'
      path: '/new'
      fullPath: '/investors/new'
      preLoaderRoute: typeof AuthenticatedInvestorsNewRouteImport
      parentRoute: typeof AuthenticatedInvestorsRoute
    }
    '/_authenticated/investors/$id': {
      id: '/_authenticated/investors/$id'
      path: '/$id'
      fullPath: '/investors/$id'
      preLoaderRoute: typeof AuthenticatedInvestorsIdRouteImport
      parentRoute: typeof AuthenticatedInvestorsRoute
    }
    '/_authenticated/global-startups/browse': {
      id: '/_authenticated/global-startups/browse'
      path: '/global-startups/browse'
      fullPath: '/global-startups/browse'
      preLoaderRoute: typeof AuthenticatedGlobalStartupsBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/global-startups/$id': {
      id: '/_authenticated/global-startups/$id'
      path: '/global-startups/$id'
      fullPath: '/global-startups/$id'
      preLoaderRoute: typeof AuthenticatedGlobalStartupsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deals/new': {
      id: '/_authenticated/deals/new'
      path: '/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof AuthenticatedDealsNewRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
    '/_authenticated/deals/$id': {
      id: '/_authenticated/deals/$id'
      path: '/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AuthenticatedDealsIdRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
    '/_authenticated/startups/$id/': {
      id: '/_authenticated/startups/$id/'
      path: '/'
      fullPath: '/startups/$id/'
      preLoaderRoute: typeof AuthenticatedStartupsIdIndexRouteImport
      parentRoute: typeof AuthenticatedStartupsIdRoute
    }
    '/_authenticated/investors/$id/': {
      id: '/_authenticated/investors/$id/'
      path: '/'
      fullPath: '/investors/$id/'
      preLoaderRoute: typeof AuthenticatedInvestorsIdIndexRouteImport
      parentRoute: typeof AuthenticatedInvestorsIdRoute
    }
    '/_authenticated/deals/$id/': {
      id: '/_authenticated/deals/$id/'
      path: '/'
      fullPath: '/deals/$id/'
      preLoaderRoute: typeof AuthenticatedDealsIdIndexRouteImport
      parentRoute: typeof AuthenticatedDealsIdRoute
    }
    '/_authenticated/startups/$id/edit': {
      id: '/_authenticated/startups/$id/edit'
      path: '/edit'
      fullPath: '/startups/$id/edit'
      preLoaderRoute: typeof AuthenticatedStartupsIdEditRouteImport
      parentRoute: typeof AuthenticatedStartupsIdRoute
    }
    '/_authenticated/investors/$id/edit': {
      id: '/_authenticated/investors/$id/edit'
      path: '/edit'
      fullPath: '/investors/$id/edit'
      preLoaderRoute: typeof AuthenticatedInvestorsIdEditRouteImport
      parentRoute: typeof AuthenticatedInvestorsIdRoute
    }
  }
}

interface AuthenticatedDealsIdRouteChildren {
  AuthenticatedDealsIdIndexRoute: typeof AuthenticatedDealsIdIndexRoute
}

const AuthenticatedDealsIdRouteChildren: AuthenticatedDealsIdRouteChildren = {
  AuthenticatedDealsIdIndexRoute: AuthenticatedDealsIdIndexRoute,
}

const AuthenticatedDealsIdRouteWithChildren =
  AuthenticatedDealsIdRoute._addFileChildren(AuthenticatedDealsIdRouteChildren)

interface AuthenticatedDealsRouteChildren {
  AuthenticatedDealsIdRoute: typeof AuthenticatedDealsIdRouteWithChildren
  AuthenticatedDealsNewRoute: typeof AuthenticatedDealsNewRoute
  AuthenticatedDealsIndexRoute: typeof AuthenticatedDealsIndexRoute
}

const AuthenticatedDealsRouteChildren: AuthenticatedDealsRouteChildren = {
  AuthenticatedDealsIdRoute: AuthenticatedDealsIdRouteWithChildren,
  AuthenticatedDealsNewRoute: AuthenticatedDealsNewRoute,
  AuthenticatedDealsIndexRoute: AuthenticatedDealsIndexRoute,
}

const AuthenticatedDealsRouteWithChildren =
  AuthenticatedDealsRoute._addFileChildren(AuthenticatedDealsRouteChildren)

interface AuthenticatedInvestorsIdRouteChildren {
  AuthenticatedInvestorsIdEditRoute: typeof AuthenticatedInvestorsIdEditRoute
  AuthenticatedInvestorsIdIndexRoute: typeof AuthenticatedInvestorsIdIndexRoute
}

const AuthenticatedInvestorsIdRouteChildren: AuthenticatedInvestorsIdRouteChildren =
  {
    AuthenticatedInvestorsIdEditRoute: AuthenticatedInvestorsIdEditRoute,
    AuthenticatedInvestorsIdIndexRoute: AuthenticatedInvestorsIdIndexRoute,
  }

const AuthenticatedInvestorsIdRouteWithChildren =
  AuthenticatedInvestorsIdRoute._addFileChildren(
    AuthenticatedInvestorsIdRouteChildren,
  )

interface AuthenticatedInvestorsRouteChildren {
  AuthenticatedInvestorsIdRoute: typeof AuthenticatedInvestorsIdRouteWithChildren
  AuthenticatedInvestorsNewRoute: typeof AuthenticatedInvestorsNewRoute
  AuthenticatedInvestorsIndexRoute: typeof AuthenticatedInvestorsIndexRoute
}

const AuthenticatedInvestorsRouteChildren: AuthenticatedInvestorsRouteChildren =
  {
    AuthenticatedInvestorsIdRoute: AuthenticatedInvestorsIdRouteWithChildren,
    AuthenticatedInvestorsNewRoute: AuthenticatedInvestorsNewRoute,
    AuthenticatedInvestorsIndexRoute: AuthenticatedInvestorsIndexRoute,
  }

const AuthenticatedInvestorsRouteWithChildren =
  AuthenticatedInvestorsRoute._addFileChildren(
    AuthenticatedInvestorsRouteChildren,
  )

interface AuthenticatedSharedDealsRouteChildren {
  AuthenticatedSharedDealsIdRoute: typeof AuthenticatedSharedDealsIdRoute
  AuthenticatedSharedDealsIndexRoute: typeof AuthenticatedSharedDealsIndexRoute
}

const AuthenticatedSharedDealsRouteChildren: AuthenticatedSharedDealsRouteChildren =
  {
    AuthenticatedSharedDealsIdRoute: AuthenticatedSharedDealsIdRoute,
    AuthenticatedSharedDealsIndexRoute: AuthenticatedSharedDealsIndexRoute,
  }

const AuthenticatedSharedDealsRouteWithChildren =
  AuthenticatedSharedDealsRoute._addFileChildren(
    AuthenticatedSharedDealsRouteChildren,
  )

interface AuthenticatedStartupsIdRouteChildren {
  AuthenticatedStartupsIdEditRoute: typeof AuthenticatedStartupsIdEditRoute
  AuthenticatedStartupsIdIndexRoute: typeof AuthenticatedStartupsIdIndexRoute
}

const AuthenticatedStartupsIdRouteChildren: AuthenticatedStartupsIdRouteChildren =
  {
    AuthenticatedStartupsIdEditRoute: AuthenticatedStartupsIdEditRoute,
    AuthenticatedStartupsIdIndexRoute: AuthenticatedStartupsIdIndexRoute,
  }

const AuthenticatedStartupsIdRouteWithChildren =
  AuthenticatedStartupsIdRoute._addFileChildren(
    AuthenticatedStartupsIdRouteChildren,
  )

interface AuthenticatedStartupsRouteChildren {
  AuthenticatedStartupsIdRoute: typeof AuthenticatedStartupsIdRouteWithChildren
  AuthenticatedStartupsNewRoute: typeof AuthenticatedStartupsNewRoute
  AuthenticatedStartupsIndexRoute: typeof AuthenticatedStartupsIndexRoute
}

const AuthenticatedStartupsRouteChildren: AuthenticatedStartupsRouteChildren = {
  AuthenticatedStartupsIdRoute: AuthenticatedStartupsIdRouteWithChildren,
  AuthenticatedStartupsNewRoute: AuthenticatedStartupsNewRoute,
  AuthenticatedStartupsIndexRoute: AuthenticatedStartupsIndexRoute,
}

const AuthenticatedStartupsRouteWithChildren =
  AuthenticatedStartupsRoute._addFileChildren(
    AuthenticatedStartupsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccessManagementRoute: typeof AuthenticatedAccessManagementRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRouteWithChildren
  AuthenticatedIntakeQueueRoute: typeof AuthenticatedIntakeQueueRoute
  AuthenticatedInvestorsRoute: typeof AuthenticatedInvestorsRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSharedDealsRoute: typeof AuthenticatedSharedDealsRouteWithChildren
  AuthenticatedStartupsRoute: typeof AuthenticatedStartupsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGlobalStartupsIdRoute: typeof AuthenticatedGlobalStartupsIdRoute
  AuthenticatedGlobalStartupsBrowseRoute: typeof AuthenticatedGlobalStartupsBrowseRoute
  AuthenticatedSettingsDefaultIntakeRoute: typeof AuthenticatedSettingsDefaultIntakeRoute
  AuthenticatedGlobalStartupsIndexRoute: typeof AuthenticatedGlobalStartupsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccessManagementRoute: AuthenticatedAccessManagementRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealsRoute: AuthenticatedDealsRouteWithChildren,
  AuthenticatedIntakeQueueRoute: AuthenticatedIntakeQueueRoute,
  AuthenticatedInvestorsRoute: AuthenticatedInvestorsRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSharedDealsRoute: AuthenticatedSharedDealsRouteWithChildren,
  AuthenticatedStartupsRoute: AuthenticatedStartupsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGlobalStartupsIdRoute: AuthenticatedGlobalStartupsIdRoute,
  AuthenticatedGlobalStartupsBrowseRoute:
    AuthenticatedGlobalStartupsBrowseRoute,
  AuthenticatedSettingsDefaultIntakeRoute:
    AuthenticatedSettingsDefaultIntakeRoute,
  AuthenticatedGlobalStartupsIndexRoute: AuthenticatedGlobalStartupsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Sp2GatewayIndexRoute: Sp2GatewayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
