/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedStartupsRouteImport } from './routes/_authenticated/startups'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated/preferences'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedInvestorsRouteImport } from './routes/_authenticated/investors'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAccessManagementRouteImport } from './routes/_authenticated/access-management'
import { Route as AuthenticatedStartupsNewRouteImport } from './routes/_authenticated/startups.new'
import { Route as AuthenticatedStartupsIdRouteImport } from './routes/_authenticated/startups.$id'
import { Route as AuthenticatedInvestorsNewRouteImport } from './routes/_authenticated/investors.new'
import { Route as AuthenticatedInvestorsIdRouteImport } from './routes/_authenticated/investors.$id'
import { Route as AuthenticatedDealsNewRouteImport } from './routes/_authenticated/deals.new'
import { Route as AuthenticatedDealsIdRouteImport } from './routes/_authenticated/deals.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStartupsRoute = AuthenticatedStartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvestorsRoute = AuthenticatedInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccessManagementRoute =
  AuthenticatedAccessManagementRouteImport.update({
    id: '/access-management',
    path: '/access-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStartupsNewRoute =
  AuthenticatedStartupsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedStartupsRoute,
  } as any)
const AuthenticatedStartupsIdRoute = AuthenticatedStartupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStartupsRoute,
} as any)
const AuthenticatedInvestorsNewRoute =
  AuthenticatedInvestorsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInvestorsRoute,
  } as any)
const AuthenticatedInvestorsIdRoute =
  AuthenticatedInvestorsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedInvestorsRoute,
  } as any)
const AuthenticatedDealsNewRoute = AuthenticatedDealsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedDealsRoute,
} as any)
const AuthenticatedDealsIdRoute = AuthenticatedDealsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDealsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/access-management': typeof AuthenticatedAccessManagementRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRouteWithChildren
  '/investors': typeof AuthenticatedInvestorsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/startups': typeof AuthenticatedStartupsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/deals/new': typeof AuthenticatedDealsNewRoute
  '/investors/$id': typeof AuthenticatedInvestorsIdRoute
  '/investors/new': typeof AuthenticatedInvestorsNewRoute
  '/startups/$id': typeof AuthenticatedStartupsIdRoute
  '/startups/new': typeof AuthenticatedStartupsNewRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/access-management': typeof AuthenticatedAccessManagementRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRouteWithChildren
  '/investors': typeof AuthenticatedInvestorsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/startups': typeof AuthenticatedStartupsRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/deals/new': typeof AuthenticatedDealsNewRoute
  '/investors/$id': typeof AuthenticatedInvestorsIdRoute
  '/investors/new': typeof AuthenticatedInvestorsNewRoute
  '/startups/$id': typeof AuthenticatedStartupsIdRoute
  '/startups/new': typeof AuthenticatedStartupsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/access-management': typeof AuthenticatedAccessManagementRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deals': typeof AuthenticatedDealsRouteWithChildren
  '/_authenticated/investors': typeof AuthenticatedInvestorsRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/startups': typeof AuthenticatedStartupsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/deals/$id': typeof AuthenticatedDealsIdRoute
  '/_authenticated/deals/new': typeof AuthenticatedDealsNewRoute
  '/_authenticated/investors/$id': typeof AuthenticatedInvestorsIdRoute
  '/_authenticated/investors/new': typeof AuthenticatedInvestorsNewRoute
  '/_authenticated/startups/$id': typeof AuthenticatedStartupsIdRoute
  '/_authenticated/startups/new': typeof AuthenticatedStartupsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/access-management'
    | '/audit'
    | '/dashboard'
    | '/deals'
    | '/investors'
    | '/notifications'
    | '/preferences'
    | '/security'
    | '/startups'
    | '/users'
    | '/deals/$id'
    | '/deals/new'
    | '/investors/$id'
    | '/investors/new'
    | '/startups/$id'
    | '/startups/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/access-management'
    | '/audit'
    | '/dashboard'
    | '/deals'
    | '/investors'
    | '/notifications'
    | '/preferences'
    | '/security'
    | '/startups'
    | '/users'
    | '/'
    | '/deals/$id'
    | '/deals/new'
    | '/investors/$id'
    | '/investors/new'
    | '/startups/$id'
    | '/startups/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/access-management'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/deals'
    | '/_authenticated/investors'
    | '/_authenticated/notifications'
    | '/_authenticated/preferences'
    | '/_authenticated/security'
    | '/_authenticated/startups'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/deals/$id'
    | '/_authenticated/deals/new'
    | '/_authenticated/investors/$id'
    | '/_authenticated/investors/new'
    | '/_authenticated/startups/$id'
    | '/_authenticated/startups/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/startups': {
      id: '/_authenticated/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof AuthenticatedStartupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investors': {
      id: '/_authenticated/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof AuthenticatedInvestorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/access-management': {
      id: '/_authenticated/access-management'
      path: '/access-management'
      fullPath: '/access-management'
      preLoaderRoute: typeof AuthenticatedAccessManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/startups/new': {
      id: '/_authenticated/startups/new'
      path: '/new'
      fullPath: '/startups/new'
      preLoaderRoute: typeof AuthenticatedStartupsNewRouteImport
      parentRoute: typeof AuthenticatedStartupsRoute
    }
    '/_authenticated/startups/$id': {
      id: '/_authenticated/startups/$id'
      path: '/$id'
      fullPath: '/startups/$id'
      preLoaderRoute: typeof AuthenticatedStartupsIdRouteImport
      parentRoute: typeof AuthenticatedStartupsRoute
    }
    '/_authenticated/investors/new': {
      id: '/_authenticated/investors/new'
      path: '/new'
      fullPath: '/investors/new'
      preLoaderRoute: typeof AuthenticatedInvestorsNewRouteImport
      parentRoute: typeof AuthenticatedInvestorsRoute
    }
    '/_authenticated/investors/$id': {
      id: '/_authenticated/investors/$id'
      path: '/$id'
      fullPath: '/investors/$id'
      preLoaderRoute: typeof AuthenticatedInvestorsIdRouteImport
      parentRoute: typeof AuthenticatedInvestorsRoute
    }
    '/_authenticated/deals/new': {
      id: '/_authenticated/deals/new'
      path: '/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof AuthenticatedDealsNewRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
    '/_authenticated/deals/$id': {
      id: '/_authenticated/deals/$id'
      path: '/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AuthenticatedDealsIdRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
  }
}

interface AuthenticatedDealsRouteChildren {
  AuthenticatedDealsIdRoute: typeof AuthenticatedDealsIdRoute
  AuthenticatedDealsNewRoute: typeof AuthenticatedDealsNewRoute
}

const AuthenticatedDealsRouteChildren: AuthenticatedDealsRouteChildren = {
  AuthenticatedDealsIdRoute: AuthenticatedDealsIdRoute,
  AuthenticatedDealsNewRoute: AuthenticatedDealsNewRoute,
}

const AuthenticatedDealsRouteWithChildren =
  AuthenticatedDealsRoute._addFileChildren(AuthenticatedDealsRouteChildren)

interface AuthenticatedInvestorsRouteChildren {
  AuthenticatedInvestorsIdRoute: typeof AuthenticatedInvestorsIdRoute
  AuthenticatedInvestorsNewRoute: typeof AuthenticatedInvestorsNewRoute
}

const AuthenticatedInvestorsRouteChildren: AuthenticatedInvestorsRouteChildren =
  {
    AuthenticatedInvestorsIdRoute: AuthenticatedInvestorsIdRoute,
    AuthenticatedInvestorsNewRoute: AuthenticatedInvestorsNewRoute,
  }

const AuthenticatedInvestorsRouteWithChildren =
  AuthenticatedInvestorsRoute._addFileChildren(
    AuthenticatedInvestorsRouteChildren,
  )

interface AuthenticatedStartupsRouteChildren {
  AuthenticatedStartupsIdRoute: typeof AuthenticatedStartupsIdRoute
  AuthenticatedStartupsNewRoute: typeof AuthenticatedStartupsNewRoute
}

const AuthenticatedStartupsRouteChildren: AuthenticatedStartupsRouteChildren = {
  AuthenticatedStartupsIdRoute: AuthenticatedStartupsIdRoute,
  AuthenticatedStartupsNewRoute: AuthenticatedStartupsNewRoute,
}

const AuthenticatedStartupsRouteWithChildren =
  AuthenticatedStartupsRoute._addFileChildren(
    AuthenticatedStartupsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccessManagementRoute: typeof AuthenticatedAccessManagementRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRouteWithChildren
  AuthenticatedInvestorsRoute: typeof AuthenticatedInvestorsRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedStartupsRoute: typeof AuthenticatedStartupsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccessManagementRoute: AuthenticatedAccessManagementRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealsRoute: AuthenticatedDealsRouteWithChildren,
  AuthenticatedInvestorsRoute: AuthenticatedInvestorsRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedStartupsRoute: AuthenticatedStartupsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
